//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class carga_puntos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carga_puntos()
        {
            this.canje_premios_detalle = new HashSet<canje_premios_detalle>();
        }
    
        public int id { get; set; }
        public int socio_id { get; set; }
        public int tipo_beneficio_id { get; set; }
        public decimal monto_cargado { get; set; }
        public decimal puntos_cargados { get; set; }
        public decimal tipo_beneficio_monto { get; set; }
        public decimal tipo_beneficio_puntos { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public string usuario_alta { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int complejo_id { get; set; }
        public decimal puntos_disponibles { get; set; }
    
        public virtual complejo complejo { get; set; }
        public virtual tipo_beneficio tipo_beneficio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<canje_premios_detalle> canje_premios_detalle { get; set; }
        public virtual socio socio { get; set; }
    }
}
