//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class complejo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public complejo()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.premios = new HashSet<premio>();
            this.carga_puntos = new HashSet<carga_puntos>();
            this.canje_premios = new HashSet<canje_premios>();
            this.canje_premios1 = new HashSet<canje_premios>();
            this.socios = new HashSet<socio>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public string usuario_alta { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string usuario_baja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<premio> premios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carga_puntos> carga_puntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<canje_premios> canje_premios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<canje_premios> canje_premios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<socio> socios { get; set; }
    }
}
