//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class premio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public premio()
        {
            this.canje_premios = new HashSet<canje_premios>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion_larga { get; set; }
        public decimal puntos { get; set; }
        public Nullable<int> complejo_responsable_id { get; set; }
        public bool desactivado { get; set; }
        public string usuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public string usuario_modificacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public string path_imagenes { get; set; }
    
        public virtual complejo complejo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<canje_premios> canje_premios { get; set; }
    }
}
