//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_beneficio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipo_beneficio()
        {
            this.carga_puntos = new HashSet<carga_puntos>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public string usuario_alta { get; set; }
        public decimal monto_dinero { get; set; }
        public decimal puntos { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public byte[] usuario_baja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carga_puntos> carga_puntos { get; set; }
    }
}
